name: E2E Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ubuntu-20.04,  Node.js 14.x

    runs-on: ubuntu-20.04
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js "14.x"
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Use Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout opensumi/core
        uses: actions/checkout@master
        with:
          repository: opensumi/core
          path: ./opensumi

      - name: Build
        shell: bash
        working-directory: ./opensumi
        run: |
          npm i
          npm run download-extension
          npm run init

      - name: Run
        shell: bash
        working-directory: ./opensumi
        run: SUPPORT_LOAD_WORKSPACE_BY_HASH=true npm start &

      - uses: microsoft/playwright-github-action@v1
      - name: Playwright Test
        continue-on-error: false
        run: |
          npm i
          npm run init
          npm run test:ui-ci
      - name: Upload HTML report as artifact. To troubleshoot failures, extract .zip and double-click index.html.
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ env.TESTGROUP }}
          path: tools/playwright/playwright-report

      - name: Publish Playwright Report
        if: always()
        uses: peaceiris/actions-gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tools/playwright/test-results
          publish_branch: playwright-report-page
